// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// CPP_AAC
Rcpp::DataFrame CPP_AAC(const Rcpp::List& x, const std::basic_string<char>& NA_letter);
RcppExport SEXP _tidysqadv_CPP_AAC(SEXP xSEXP, SEXP NA_letterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const std::basic_string<char>& >::type NA_letter(NA_letterSEXP);
    rcpp_result_gen = Rcpp::wrap(CPP_AAC(x, NA_letter));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tidysqadv_CPP_AAC", (DL_FUNC) &_tidysqadv_CPP_AAC, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_tidysqadv(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
