# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CPP_AAC <- function(x, NA_letter) {
    .Call(`_tidysqadv_CPP_AAC`, x, NA_letter)
}

